//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica4
{
    using System;
    using System.Collections.Generic;
    
    public partial class credito
    {
        public int codigo { get; set; }
        public Nullable<float> Monto { get; set; }
        public string Descripcion { get; set; }
        public string estado { get; set; }
        public Nullable<int> cuenta { get; set; }
    
        public virtual cuenta cuenta1 { get; set; }
    }
}
