//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento
    {
        public int codigo { get; set; }
        public Nullable<float> Monto { get; set; }
        public string mov { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cuentaUno { get; set; }
        public Nullable<int> cuentaDos { get; set; }
    
        public virtual cuenta cuenta { get; set; }
        public virtual cuenta cuenta1 { get; set; }
    }
}
